package de.mannodermaus.gradle.plugins.junit5

import de.mannodermaus.gradle.plugins.junit5.dsl.AndroidJUnitPlatformExtension
import org.gradle.api.Project
import de.mannodermaus.gradle.plugins.junit5.internal.extensions.junitPlatform as junitPlatform_internal

@Deprecated(
        message = "This property is no longer necessary - " +
                "please use the accessor generated by Gradle's Kotlin DSL instead",
        replaceWith = ReplaceWith("")
)
public val Project.junitPlatform: AndroidJUnitPlatformExtension
    get() = junitPlatform_internal

@Deprecated(
        message = "This type has moved into the 'dsl' sub-package",
        replaceWith = ReplaceWith(
                "AndroidJUnitPlatformExtension",
                "de.mannodermaus.gradle.plugins.junit5.dsl.AndroidJUnitPlatformExtension"
        )
)
public typealias AndroidJUnitPlatformExtension = de.mannodermaus.gradle.plugins.junit5.dsl.AndroidJUnitPlatformExtension

@Deprecated(
        message = "This type has moved into the 'dsl' sub-package",
        replaceWith = ReplaceWith(
                "FiltersExtension",
                "de.mannodermaus.gradle.plugins.junit5.dsl.FiltersExtension"
        )
)
public typealias FiltersExtension = de.mannodermaus.gradle.plugins.junit5.dsl.FiltersExtension

@Deprecated(
        message = "This type has moved into the 'dsl' sub-package",
        replaceWith = ReplaceWith(
                "InstrumentationTestOptions",
                "de.mannodermaus.gradle.plugins.junit5.dsl.InstrumentationTestOptions"
        )
)
public typealias InstrumentationTestOptions = de.mannodermaus.gradle.plugins.junit5.dsl.InstrumentationTestOptions

@Deprecated(
        message = "This type has moved into the 'dsl' sub-package",
        replaceWith = ReplaceWith(
                "JacocoOptions",
                "de.mannodermaus.gradle.plugins.junit5.dsl.JacocoOptions"
        )
)
public typealias JacocoOptions = de.mannodermaus.gradle.plugins.junit5.dsl.JacocoOptions
